### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by aakriti7**

### CODE REVIEW

**Comment by aakriti7** [comment]
Hi,
I have changed the folders to main and test.
I have removed the main methods from the User story classes and called them from service.
I have added the test annotations.
I wasn't actually able to test using mvn test. I executed the command and got build successful.
I have added some comments to the code.

**Comment by jmt212** [comment]
All the code is moved to a package main.java.* - was that intentional? It should not be necessary to include main.java in the package name. Are you using maven/do you have maven installed? If your using an IDE you can import the code as a maven project which may resolve some of the problems you may have been seeing.

**Comment by aakriti7** [comment]
Yes i have used maven. I was able to run my code using mvn test yesterday. I can see the code is in main and test folders separately in this branch. May be there is some confusion. Can you recheck?

**Comment by jmt212** [comment]
The maven convention (https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) is to put the project code in a set of folders under src/main/java - the package folders then begin underneath the java folder. The package names do not include main/java because they are not considered packages. At the root level of the project (at the same level as the src folder) is the pom.xml which maven uses to determine (based on the maven convention for directory layouts) where the production and test code is located.

**Comment by aakriti7** [comment]
I have added 3 files GedcomService.java, US01.java and US25.java inside main/java folder. These are the user story implementation. And I have added TestUs01.java , TestUS25.java files inside test/java folder. These are test cases implementation.

**Comment by aakriti7** [comment]
I have changed the package names.

**Comment by jmt212** [comment]
looks good!

**Pull request merged**
