### PR TITLE
Rima1993 patch 2

### PR DESCRIPTION
**Pull request by rima1993**

### CODE REVIEW

**Comment by jmt212** [comment]
https://github.com/jmt212/SSW555/blob/master/src/main/java/edu/stevens/ssw555/GedcomService.java#L284

Theres a merge at line 284 in master after your latest merge.

**Comment by rima1993** [comment]
hey,

I have rechecked all files and do some required changes in master. Now,
there is no conflicts and no errors. It is successfully completed.

Thanks,
Rimaben

**Comment by jmt212** [comment]
@rima1993 some of your test methods call out for user input. this should not happen - and it actually prevents the test from running (in maven or another test harness). you can either hard code relative file paths into the test case, or create the maps of data yourself in the code.

**Comment by rima1993** [comment]
Yes, I have just changed my Test case file named Testus03.java. Now it
don't call for user input. I am also changing TestUS04.java

Thanks,
Rimaben

**Comment by rima1993** [comment]
Hey,

I have changed all my Testcase files and also check by using mvn.
everything is working correct.
Now how will submit Project4 Assignment on canvas. From the description on
canvas *Demonstrating Sprint 1 part is remaining.*

Thanks

**Pull request merged**
