### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rima1993**
Hi,

I have uploaded file for US03 and US04 and test cases. Please let me know if there is any issue.

Thanks,
Rimaben

### CODE REVIEW

**Comment by jmt212** [comment]
looks good!

**Comment by jmt212** [comment]
@rima1993 there are some merge conflicts with code already committed by Aakriti can you resolve them when you get the chance? Thanks!

**Comment by rima1993** [comment]
hey @jmt212, I have resolved conflicts. Can you take a look that now merge is working fine or not?
Thanks

**Comment by jmt212** [comment]
looks good! thanks!

**Comment by jmt212** [comment]
Hey @rima1993 i take that back, i merged in the branch and there are still conflicts. i'll leave comments in line to show some examples.

**Comment by rima1993** [comment]
Hey @jmt212, I don't find any open issue regarding conflict. But I have
changed some code in branch rima1993-patch-2. Can you now check with it.

**Comment by rima1993** [comment]
hey,

I have merged pull request with master branch and its successfully done. I
think all set now.

Thanks.

**Pull request merged**
